import { useState } from "react";
import { Alert, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from "react-native";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useAppState } from "@/lib/app-state";

export default function ProfileScreen() {
  const colors = useColors();
  const { profile, creations, updateProfile } = useAppState();
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState(profile);
  const [notifications, setNotifications] = useState(true);
  const [autoSave, setAutoSave] = useState(true);
  const save = () => { updateProfile(draft); setEditing(false); Alert.alert("Profile updated", "Your changes are saved on this device."); };
  return <ScreenContainer className="px-5"><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ paddingBottom: 32 }}><View style={styles.header}><View><Text style={[styles.kicker, { color: colors.primary }]}>YOUR SPACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Profile</Text></View><TouchableOpacity onPress={() => setEditing((value) => !value)} style={[styles.editButton, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name={editing ? "xmark" : "pencil"} size={17} color={colors.primary} /><Text style={{ color: colors.foreground, fontSize: 12, fontWeight: "800" }}>{editing ? "Close" : "Edit"}</Text></TouchableOpacity></View>
    <View style={[styles.profileCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.avatar, { backgroundColor: colors.primary }]}><Text style={styles.avatarText}>{profile.name.slice(0, 1)}</Text></View><View style={{ flex: 1 }}><Text style={[styles.profileName, { color: colors.foreground }]}>{profile.name}</Text><Text style={{ color: colors.muted, marginTop: 3 }}>@{profile.username}</Text><View style={styles.planRow}><View style={[styles.planDot, { backgroundColor: colors.success }]} /><Text style={{ color: colors.muted, fontSize: 11 }}>Personal workspace</Text></View></View></View>
    {editing ? <View style={[styles.formCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Field label="DISPLAY NAME" value={draft.name} onChangeText={(name: string) => setDraft({ ...draft, name })} colors={colors} /><Field label="USERNAME" value={draft.username} onChangeText={(username: string) => setDraft({ ...draft, username })} colors={colors} /><Field label="EMAIL" value={draft.email} onChangeText={(email: string) => setDraft({ ...draft, email })} colors={colors} keyboardType="email-address" /><Field label="BIO" value={draft.bio} onChangeText={(bio: string) => setDraft({ ...draft, bio })} colors={colors} multiline /><TouchableOpacity onPress={save} style={[styles.saveButton, { backgroundColor: colors.primary }]}><IconSymbol name="checkmark" size={18} color="#FFFFFF" /><Text style={styles.saveText}>Save changes</Text></TouchableOpacity></View> : <><View style={[styles.statsCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Stat value={String(creations.length)} label="Creations" colors={colors} /><Stat value={String(creations.filter((item) => item.saved).length)} label="Saved" colors={colors} /><Stat value="High" label="Default quality" colors={colors} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>Preferences</Text><View style={[styles.preferenceCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Preference icon="sparkles" title="Smart defaults" subtitle="Use high quality and auto model selection" value={autoSave} onChange={setAutoSave} colors={colors} /><Preference icon="photo.on.rectangle.angled" title="Save new creations" subtitle="Keep every result in My Creations" value={autoSave} onChange={setAutoSave} colors={colors} /><Preference icon="person.crop.circle.fill" title="Notifications" subtitle="Updates about your generations" value={notifications} onChange={setNotifications} colors={colors} /></View><Text style={[styles.sectionTitle, { color: colors.foreground }]}>More</Text><View style={[styles.preferenceCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><LinkRow title="Help & support" colors={colors} /><LinkRow title="Privacy policy" colors={colors} /><LinkRow title="Terms of service" colors={colors} /><LinkRow title="Sign out" colors={colors} destructive /></View></>}
  </ScrollView></ScreenContainer>;
}
function Field({ label, value, onChangeText, colors, multiline, keyboardType }: any) { return <View style={styles.field}><Text style={[styles.fieldLabel, { color: colors.muted }]}>{label}</Text><TextInput value={value} onChangeText={onChangeText} multiline={multiline} keyboardType={keyboardType} style={[styles.fieldInput, { color: colors.foreground, borderColor: colors.border }]} placeholderTextColor={colors.muted} /></View>; }
function Stat({ value, label, colors }: any) { return <View style={styles.stat}><Text style={[styles.statValue, { color: colors.foreground }]}>{value}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 3 }}>{label}</Text></View>; }
function Preference({ icon, title, subtitle, value, onChange, colors }: any) { return <View style={styles.preference}><View style={[styles.preferenceIcon, { backgroundColor: colors.background }]}><IconSymbol name={icon} size={18} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={{ color: colors.foreground, fontWeight: "700", fontSize: 13 }}>{title}</Text><Text style={{ color: colors.muted, fontSize: 11, marginTop: 3 }}>{subtitle}</Text></View><Switch value={value} onValueChange={onChange} trackColor={{ false: colors.border, true: colors.primary }} thumbColor="#FFFFFF" /></View>; }
function LinkRow({ title, colors, destructive }: any) { return <TouchableOpacity onPress={() => Alert.alert(title, "This section is ready for the secure backend content.")} style={styles.linkRow}><Text style={{ color: destructive ? colors.error : colors.foreground, fontWeight: "700", fontSize: 13 }}>{title}</Text><IconSymbol name="chevron.right" size={18} color={colors.muted} /></TouchableOpacity>; }
const styles = StyleSheet.create({ header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingTop: 12, paddingBottom: 20 }, kicker: { fontSize: 10, fontWeight: "800", letterSpacing: 1.4 }, title: { fontSize: 28, fontWeight: "800", marginTop: 4 }, editButton: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 14, borderWidth: 1 }, profileCard: { borderWidth: 1, borderRadius: 20, padding: 17, flexDirection: "row", alignItems: "center", gap: 13 }, avatar: { width: 58, height: 58, borderRadius: 20, alignItems: "center", justifyContent: "center" }, avatarText: { color: "#FFFFFF", fontSize: 23, fontWeight: "800" }, profileName: { fontSize: 17, fontWeight: "800" }, planRow: { flexDirection: "row", gap: 6, alignItems: "center", marginTop: 10 }, planDot: { width: 7, height: 7, borderRadius: 4 }, statsCard: { borderWidth: 1, borderRadius: 18, flexDirection: "row", justifyContent: "space-around", paddingVertical: 18, marginTop: 13 }, stat: { alignItems: "center" }, statValue: { fontSize: 18, fontWeight: "800" }, sectionTitle: { fontSize: 15, fontWeight: "800", marginTop: 25, marginBottom: 10 }, preferenceCard: { borderWidth: 1, borderRadius: 18, paddingHorizontal: 15 }, preference: { flexDirection: "row", alignItems: "center", gap: 12, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(128,128,128,0.14)" }, preferenceIcon: { width: 35, height: 35, borderRadius: 11, alignItems: "center", justifyContent: "center" }, linkRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: "rgba(128,128,128,0.14)" }, formCard: { borderWidth: 1, borderRadius: 20, padding: 16 }, field: { marginBottom: 14 }, fieldLabel: { fontSize: 10, fontWeight: "800", letterSpacing: 1.1, marginBottom: 7 }, fieldInput: { borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14, minHeight: 44 }, saveButton: { borderRadius: 14, minHeight: 50, alignItems: "center", justifyContent: "center", flexDirection: "row", gap: 8, marginTop: 3 }, saveText: { color: "#FFFFFF", fontWeight: "800" }, });
